version: "3.9"

services:
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    env_file: .env
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress

  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    networks:
      - inception
    volumes:
      - db:/var/www/html

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: "local"
      o: bind
      device: $HOME/data/wordpress
  db:
    name: db
    driver_opts:
      type: "local"
      o: bind
      device: $HOME/data/db

networks:
  inception:
    name: inception
