version: "3.9"

services:
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    env_file: .env
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_started

  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_started

  mariadb:
    build:  ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb

networks:
  inception:
    name: inception
