version: "3.9"

services:
  # wordpress:
  #  build: ./srcs/requirements/wordpress
  #  ports:
  #    - 9000
  #    - 3306
  #  networks:
  #    - inception
  #  volumes:
  #     - wp_data:/var/www/html

  nginx:
    build: ./srcs/requirements/nginx
    ports:
     - 443:443
    networks:
      - inception

#  mariadb:
#    build: ./srcs/requirements/mariadb
#    ports:
#     - 3306
#    networks:
#      - inception
#    volumes:
#     - db_data:.

volumes:
  wp_data:
  db_data:

networks:
  inception:
    name: inception
